# Generated by Django 4.1.2 on 2022-10-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_head_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="head_image",
            field=models.ImageField(
                blank=True, upload_to="_media/blog/images/%Y/%m/%d/"
            ),
        ),
    ]
